### ISSUE TITLE
Prefer tests over `type`?

### ISSUE THREAD

**Issue by MiConnell** [MiConnell/flexit-technical-interview-clone#16]
should `schema.yml` prefer tests over constraints for unique and not_null on key columns?
especially in the case of [redshift](https://docs.aws.amazon.com/redshift/latest/dg/t_Defining_constraints.html) where 

> Uniqueness, primary key, and foreign key constraints are informational only

instead of 
```yaml

models:
  - name: fact_sales
...
    columns:
      - name: fact_sales_key
        data_type: text
        meta:
          hidden: true
        constraints:
          - type: not_null
          - type: primary_key
            warn_unenforced: false
```

use this

```yaml
models:
  - name: fact_sales
...
    columns:
      - name: fact_sales_key
        data_type: text
        meta:
          hidden: true
        tests: &not_null_unique
          - not_null
          - unique
...
  - name: dim_customer
    columns:
      - name: customer_key
        data_type: text
        meta:
          label: customer_key
          hidden: true
    tests: *not_null_unique
```
